FROM node:20-alpine3.17 as development

WORKDIR /usr/src/app

COPY package*.json ./
COPY wait-for-it.sh ./
RUN chmod +x ./wait-for-it.sh
RUN npm install --only=development

COPY . .

RUN ls -la

RUN npm run build

EXPOSE 3000

FROM node:20-alpine3.17 as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]
