version: '3.7'
name: ${SERVICE_NAME}
services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: docker/server/DockerFile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "npm i && npm run start:dev"
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    build:
      context: ./docker/database
      dockerfile: DockerFile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data

networks:
  webnet:
    driver: bridge

